export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body style={
        {
          minHeight: '100vh',
          display: 'flex',
          flexDirection: 'column',
        }
      }>
        <header
          style={{
            backgroundColor: "lightblue",
            padding: "1rem",
            display: 'flex',
            justifyContent: 'center',
            alignItems: 'center',

          }}
        >
          <h1>Header</h1>
        </header>

        <main style={
          {
            flex: '1',
            display: 'flex',
            justifyContent: 'center',
            alignItems: 'center',

          }
        }>
          {children}
        </main>

        <footer
          style={{
            backgroundColor: "ghostwhite",
            padding: "1rem",
            display: 'flex',
            justifyContent: 'center',
            alignItems: 'center',

          }}
        >
          <h1>Footer</h1>
        </footer>
      </body>
    </html>
  );
}
